# CONFIDENTIAL COMPUTER CODE AND INFORMATION
# COPYRIGHT (C) VMware, INC. ALL RIGHTS RESERVED.
# REPRODUCTION BY ANY MEANS EXPRESSLY FORBIDDEN WITHOUT THE WRITTEN
# PERMISSION OF THE OWNER.
#
# WRAPPER FUNCTION OF SECURITY SCANNING FRAMEWORK
# ----------------------------------------------------------------------------
# Standard Libarary
import os

# BASE Directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# LOGS Directory
LOGS = os.path.join(BASE_DIR, 'logs')

# Python Directory
PYTHON = r'/usr/bin/python'

# Exit Code
""" 
set PASS  =  0 for Success 
set FAIL  =  1 for Failure
"""
PASS = 0	 
FAIL = 1   


# Framework Execution Type 
"""
set PARALLEL = True|YES|Yes|yes|y for Parallel Execution 
set PARALLEL = False|NO|No|no|n for Sequential Execution 
"""
PARALLEL = False   


# Applications
APPS = {'webapps'  :{'name'  : 'Web Application',   						# Application Name
		     'job'   : 'WebApplicationSecurityAutomationFramework',			# Jenkins Jobname
                     'header': ['Vulnerability Name','Severity','Affected URL','Jira BUG ID'],  # Defects Header
		     'cmd'   : [PYTHON, os.path.join(BASE_DIR, 'webapps', 'automation.py')]      # Backend script 
                     },  
        'apiconfig':{'name'  : 'Api Configuration',
		     'job'   : 'APISecurityAssessmentAutomation',
                     'header': ['API Name','Vulnerability','Test Result','Risk Rating','Vulnerability Category','Remarks','Jira BUG ID'],
		     'cmd'   : [PYTHON, os.path.join(BASE_DIR, 'apiconfig', 'automation.py')] 
		     },
        'sca'      :{'name'  : 'Static Code Analysis',
		     'job'   : 'FortifyContinuousIntegrationOnDemandSCA',
                     'header': [],
		     'cmd'   : [PYTHON, os.path.join(BASE_DIR, 'sca', 'automation.py')] 
		     }
        }


# Jenkins Settings
JENKINS_CONFIG = {'SERVER': 'http://10.127.240.50:8080',
	          'MASTER': '10.127.235.84',
	          'NODE-1': '10.127.234.225',
	          'NODE-2': '10.127.234.12',
                  'STATUS': {'SUCCESS'  : (PASS, 'The build had no errors...'),
			     'FAILURE'  : (FAIL, 'The build had a fatal error...'),
			     'ABORTED'  : (FAIL, 'The build was manually aborted...'),
			     'UNSTABLE' : (FAIL, 'The build had some errors but they were not fatal...'),
			     'NOT_BUILT': (FAIL, 'The module was not built...')
                             },
		  'WAIT'  : 10,         # On trigerring build, wait for specifed seconds to fetch build_id
		  'VERIFY': 25,         # Verify build status for specified seconds
		  'URL_TIMEOUT': 60,	# HTTP CONSOLE URL TIMEOUT
		  'URL_RETRY': 3	# HTTP CONSOLE TXT READING FOR EXTRACING THE REPORTS 
                  }


# Webserver Settings
WEBSERVER_CONFIG = {'ROOT'  : '/data/security_automation/it-app-sec/',     # Document Root is set to Drive D:
		    'MASTER': 'http://10.127.240.50/',
		    'NODE_1': 'http://10.127.240.50/',
                    'NODE_2': 'http://10.127.240.50/',
		    }


# Perforce Settings
P4_CONFIG = { 
'SERVER': 'perforce-it.vmware.com',
'PORT': '1947',
'USERNAME': 'deployadmin',
'PASSWORD': 'Y3y5A!u@U.Y.uMu3E.y',
'CLIENT': 'deployadmin_itappsec',
'ROOT': '/data/p4_workspace'
}


# Database Settings
DB_CONFIG = {
'HOST': 'host',  
'USERNAME': 'username',
'PASSWORD': 'password',
'DATABASE': 'db_name'
}


# Jira Settings
JIRA_CONFIG = {
'USERNAME': 'deployadmin',
'PASSWORD': 'password',
'SERVER': 'https://vmware-it.atlassian.net',
'PROJECT': 'project',
'ISSUETYPE': 'Bug'
}

# Mail Settings
MAIL_CONFIG = {
'FROM': 'it-app-sec@vmware.com',
'TO': ['shivarajs@vmware.com','pankaja@vmware.com','jashutosh@vmware.com'],
#'TO': ['jashutosh@vmware.com'],
'CC': ['psudan@vmware.com','patelm@vmware.com','sjingu@vmware.com'],
#'CC': ['jashutosh@vmware.com'],
'SUB': 'Nighlty Runs: Security Scan On ',
'HEADER': ['Sl.', 'Artifact', 'Start Time', 'End Time', 'Duration', 'Status', 'Console', 'Report']
}

# EMAIL NOTIFICATION TEMPLATE
NOTIFICATION = r"""
<html><head><title>::: Security Scan :::</title></head>
<body><font face='garamond' size='3'><br/>
****************************************************************************************************<br/>
&nbsp;&nbsp; This is an autogenerated email. Please contact automation team for any clarifications. <br/>
****************************************************************************************************<br/>
<br/><b>Security Analysis Report</b>
<br/><b>Application Type:</b>&nbsp;&nbsp;{{ app_name }}
<br/><b>Project Name:</b>&nbsp;&nbsp;{{ project_name }}
<br/><b>RFC:</b>&nbsp;&nbsp;{{ rfc }}
<br/><b>vRCS Execution ID:</b>&nbsp;&nbsp;{{ vrcs_exec_id }}<br/><br/>
<table border=1 cellpadding=5 cellspacing=0 bordercolor='black' style='font-family:garamond;'><tbody>
<tr>
{% for head in header %}
   <th nowrap>{{ head }}</th>
{% endfor %}
</tr>
{% for row in rows %}
   <tr>
     <td nowrap>{{ row.0 }}</td>
     <td nowrap>{{ row.1 }}</td>
     <td nowrap>{{ row.2 }}</td>
     <td nowrap>{{ row.3 }}</td>
     <td nowrap>{{ row.4 }}</td>
     <td nowrap>{{ row.5 }}</td>
     <td nowrap><a href="{{ row.6 }}">Console</a></td>
     <td nowrap><a href="{{ row.7 }}">Report</a></td>
   </tr>
{% endfor %}
</tbody></table>
<br/><br/>Thanks,<br/>Security Automation Team <br/>
<br/><br/></font></body></html>
"""
