# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Host Audit
    displayName: Scan host for configuration
    jobs:
      - job: Inspec
        displayName: Install and run inspec
        steps:
          - script: |
              sudo dpkg -i ./inspec.deb
              inspec exec https://github.com/dev-sec/cis-docker-benchmark
  # - stage: SCA & SAST
  # - stage: Deploy
  # - stage: DAST

